database deployment

diff --git a/builds/pipelines/templates/steps/databases-cd-steps.yaml b/builds/pipelines/templates/steps/databases-cd-steps.yaml
--- a/builds/pipelines/templates/steps/databases-cd-steps.yaml
+++ b/builds/pipelines/templates/steps/databases-cd-steps.yaml
@@ -2,6 +2,26 @@
 # -----------------------------------------------------------------------------
 # Deploy Database
 # -----------------------------------------------------------------------------
+parameters:
+  - name: aksResourceGroup
+    type: string
+
+  - name: aksName
+    type: string
+
+  - name: serviceName
+    type: string
+
+  - name: databaseName
+    type: string
+
+  - name: databaseUserName
+    type: string
+
+  - name: databaseUserPassword
+    type: string
+
+
 steps:
   - checkout: self
     displayName: "Checkout repository"
@@ -14,53 +34,79 @@ steps:
       scriptLocation: 'inlineScript'
       inlineScript: |
         # Get credentials
-        az aks get-credentials --resource-group rg-aks-bootstrap-networking-spoke --name aksbootstrap --admin
+        az aks get-credentials --resource-group ${{ parameters.aksResourceGroup }} --name ${{ parameters.aksName }} --admin
 
         # Copy files to pods
-        kubectl cp ./databases/configuration/createUsers.sql  postgresql-0:/tmp/createUsers.sql -c postgresql -n postgresql
-        kubectl cp ./databases/configuration/configurationDB.sql  postgresql-0:/tmp/configurationDB.sql -c postgresql -n postgresql
-        kubectl cp ./databases/configuration/grantUsers.sql  postgresql-0:/tmp/grantUsers.sql -c postgresql -n postgresql
+        if (Test-Path -Path "./databases/${{ parameters.serviceName }}/createUsers.sql" -PathType Leaf)
+        {
+          echo "Database ${{ parameters.serviceName }} has a createUsers sql script"
+          kubectl cp ./databases/${{ parameters.serviceName }}/createUsers.sql  postgresql-0:/tmp/createUsers.sql -c postgresql -n postgresql
+          echo "##vso[task.setvariable variable=hasCreateUsers]$true"
+        }
+
+        if (-not(Test-Path -Path "./databases/${{ parameters.serviceName }}/configurationDB.sql" -PathType Leaf))
+        {
+          echo "##[error]Database ${{ parameters.serviceName }} has no sql script"
+          exit 1
+        }
+        kubectl cp ./databases/${{ parameters.serviceName }}/configurationDB.sql  postgresql-0:/tmp/configurationDB.sql -c postgresql -n postgresql
+
+
+        if (Test-Path -Path "./databases/${{ parameters.serviceName }}/grantUsers.sql" -PathType Leaf)
+        {
+          echo "Database ${{ parameters.serviceName }} has a grantUsers sql script"
+          kubectl cp ./databases/${{ parameters.serviceName }}/grantUsers.sql  postgresql-0:/tmp/grantUsers.sql -c postgresql -n postgresql
+          echo "##vso[task.setvariable variable=hasGrantUsers]$true"
+        }
+
+
 
   - task: Kubernetes@1
     displayName: "Create User"
     inputs:
       connectionType: 'Azure Resource Manager'
       azureSubscriptionEndpoint: 'Ansible-Automation'
-      azureResourceGroup: 'rg-aks-bootstrap-networking-spoke'
-      kubernetesCluster: 'aksbootstrap'
+      azureResourceGroup: '${{ parameters.aksResourceGroup }}'
+      kubernetesCluster: '${{ parameters.aksName }}'
       namespace: 'postgresql'
       command: 'exec'
       arguments: >-
         postgresql-0 -c postgresql -n postgresql
-        -- psql postgresql://inventorydb-admin:$(inventorydb-admin)@postgresql/ConfigurationDB
+        -- psql postgresql://inventorydb-admin:$(inventorydb-admin)@postgresql/${{ parameters.databaseName }}
         -f /tmp/createUsers.sql
+    condition: and(
+      succeeded(),
+      eq(variables['hasCreateUsers'], 'True')
+    )
 
   - task: Kubernetes@1
     displayName: "Set User password"
     inputs:
       connectionType: 'Azure Resource Manager'
       azureSubscriptionEndpoint: 'Ansible-Automation'
-      azureResourceGroup: 'rg-aks-bootstrap-networking-spoke'
-      kubernetesCluster: 'aksbootstrap'
+      azureResourceGroup: '${{ parameters.aksResourceGroup }}'
+      kubernetesCluster: '${{ parameters.aksName }}'
       namespace: 'postgresql'
       command: 'exec'
       arguments: >-
         postgresql-0 -c postgresql -n postgresql
-        -- psql postgresql://inventorydb-admin:$(inventorydb-admin)@postgresql/ConfigurationDB
-        -c "ALTER USER configurationdb_rw WITH PASSWORD '$(configurationdb-rw)'"
+        -- psql postgresql://inventorydb-admin:$(inventorydb-admin)@postgresql/${{ parameters.databaseName }}
+        -c "ALTER USER ${{ parameters.databaseUserName }} WITH PASSWORD '$USER_PASSWORD'"
+    env:
+      USER_PASSWORD: '${{ parameters.databaseUserPassword }}'
 
   - task: Kubernetes@1
     displayName: "Create Database objects"
     inputs:
       connectionType: 'Azure Resource Manager'
       azureSubscriptionEndpoint: 'Ansible-Automation'
-      azureResourceGroup: 'rg-aks-bootstrap-networking-spoke'
-      kubernetesCluster: 'aksbootstrap'
+      azureResourceGroup: '${{ parameters.aksResourceGroup }}'
+      kubernetesCluster: '${{ parameters.aksName }}'
       namespace: 'postgresql'
       command: 'exec'
       arguments: >-
         postgresql-0 -c postgresql -n postgresql
-        -- psql postgresql://inventorydb-admin:$(inventorydb-admin)@postgresql/ConfigurationDB
+        -- psql postgresql://inventorydb-admin:$(inventorydb-admin)@postgresql/${{ parameters.databaseName }}
         -f /tmp/configurationDB.sql
 
   - task: Kubernetes@1
@@ -68,11 +114,15 @@ steps:
     inputs:
       connectionType: 'Azure Resource Manager'
       azureSubscriptionEndpoint: 'Ansible-Automation'
-      azureResourceGroup: 'rg-aks-bootstrap-networking-spoke'
-      kubernetesCluster: 'aksbootstrap'
+      azureResourceGroup: '${{ parameters.aksResourceGroup }}'
+      kubernetesCluster: '${{ parameters.aksName }}'
       namespace: 'postgresql'
       command: 'exec'
       arguments: >-
         postgresql-0 -c postgresql -n postgresql
-        -- psql postgresql://inventorydb-admin:$(inventorydb-admin)@postgresql/ConfigurationDB
+        -- psql postgresql://inventorydb-admin:$(inventorydb-admin)@postgresql/${{ parameters.databaseName }}
         -f /tmp/grantUsers.sql
+    condition: and(
+      succeeded(),
+      eq(variables['hasCreateUsers'], 'True')
+    )
